# Project information
site_name: Python by c17hawke
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Introduction to Python:
      - pdf: noteboooks/000-intro-to-python/python_notes_updated.pdf
  # - Introduction to Python: noteboooks/000-intro-to-python/notes.md
  - Getting started: noteboooks/001-getting-started/notes.ipynb
  - Variables: noteboooks/002-variables-in-python/notes.ipynb

site_author: Sunny Bhaveen Chandra
site_description: >-
  Python for beginners

# Repository
repo_name: c17hawke/Python
repo_url: https://github.com/c17hawke/Python

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: cyan
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: cyan
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/c17hawke
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c17hawke
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/c17hawke/

extra_javascript:
  - javascripts/mathjax.js
  # - javascripts/tawk.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.pathconverter:
      base_path: 'Python'
      relative_path: ''
      absolute: true
      tags: 'a script img link object embed'

plugins:
  - search
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      include_source: True

copyright: |
  &copy; 2023 <a href="https://github.com/c17hawke"  target="_blank" rel="noopener">Sunny Bhaveen Chandra</a>